// Code generated by protoc-gen-go.
// source: api.proto
// DO NOT EDIT!

/*
Package types is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	StartJobRequest
	StartJobResponse
	DeleteJobRequest
	DeleteJobResponse
	ListJobsRequest
	Job
	ListJobsResponse
	StateRequest
	StateResponse
	LogsRequest
	Log
*/
package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type StartJobRequest struct {
	Name      string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Args      []string `protobuf:"bytes,2,rep,name=args" json:"args,omitempty"`
	Artifacts string   `protobuf:"bytes,3,opt,name=artifacts" json:"artifacts,omitempty"`
}

func (m *StartJobRequest) Reset()                    { *m = StartJobRequest{} }
func (m *StartJobRequest) String() string            { return proto.CompactTextString(m) }
func (*StartJobRequest) ProtoMessage()               {}
func (*StartJobRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type StartJobResponse struct {
	Id uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *StartJobResponse) Reset()                    { *m = StartJobResponse{} }
func (m *StartJobResponse) String() string            { return proto.CompactTextString(m) }
func (*StartJobResponse) ProtoMessage()               {}
func (*StartJobResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type DeleteJobRequest struct {
	Id uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteJobRequest) Reset()                    { *m = DeleteJobRequest{} }
func (m *DeleteJobRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteJobRequest) ProtoMessage()               {}
func (*DeleteJobRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type DeleteJobResponse struct {
}

func (m *DeleteJobResponse) Reset()                    { *m = DeleteJobResponse{} }
func (m *DeleteJobResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteJobResponse) ProtoMessage()               {}
func (*DeleteJobResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type ListJobsRequest struct {
}

func (m *ListJobsRequest) Reset()                    { *m = ListJobsRequest{} }
func (m *ListJobsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListJobsRequest) ProtoMessage()               {}
func (*ListJobsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type Job struct {
	Id        uint32   `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name      string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Args      []string `protobuf:"bytes,3,rep,name=args" json:"args,omitempty"`
	Artifacts string   `protobuf:"bytes,4,opt,name=artifacts" json:"artifacts,omitempty"`
	Status    string   `protobuf:"bytes,5,opt,name=status" json:"status,omitempty"`
}

func (m *Job) Reset()                    { *m = Job{} }
func (m *Job) String() string            { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()               {}
func (*Job) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type ListJobsResponse struct {
	Jobs []*Job `protobuf:"bytes,1,rep,name=jobs" json:"jobs,omitempty"`
}

func (m *ListJobsResponse) Reset()                    { *m = ListJobsResponse{} }
func (m *ListJobsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListJobsResponse) ProtoMessage()               {}
func (*ListJobsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ListJobsResponse) GetJobs() []*Job {
	if m != nil {
		return m.Jobs
	}
	return nil
}

type StateRequest struct {
	Id uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *StateRequest) Reset()                    { *m = StateRequest{} }
func (m *StateRequest) String() string            { return proto.CompactTextString(m) }
func (*StateRequest) ProtoMessage()               {}
func (*StateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type StateResponse struct {
	Status string `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *StateResponse) Reset()                    { *m = StateResponse{} }
func (m *StateResponse) String() string            { return proto.CompactTextString(m) }
func (*StateResponse) ProtoMessage()               {}
func (*StateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type LogsRequest struct {
	Id uint32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *LogsRequest) Reset()                    { *m = LogsRequest{} }
func (m *LogsRequest) String() string            { return proto.CompactTextString(m) }
func (*LogsRequest) ProtoMessage()               {}
func (*LogsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type Log struct {
	Log string `protobuf:"bytes,1,opt,name=log" json:"log,omitempty"`
}

func (m *Log) Reset()                    { *m = Log{} }
func (m *Log) String() string            { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()               {}
func (*Log) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func init() {
	proto.RegisterType((*StartJobRequest)(nil), "types.StartJobRequest")
	proto.RegisterType((*StartJobResponse)(nil), "types.StartJobResponse")
	proto.RegisterType((*DeleteJobRequest)(nil), "types.DeleteJobRequest")
	proto.RegisterType((*DeleteJobResponse)(nil), "types.DeleteJobResponse")
	proto.RegisterType((*ListJobsRequest)(nil), "types.ListJobsRequest")
	proto.RegisterType((*Job)(nil), "types.Job")
	proto.RegisterType((*ListJobsResponse)(nil), "types.ListJobsResponse")
	proto.RegisterType((*StateRequest)(nil), "types.StateRequest")
	proto.RegisterType((*StateResponse)(nil), "types.StateResponse")
	proto.RegisterType((*LogsRequest)(nil), "types.LogsRequest")
	proto.RegisterType((*Log)(nil), "types.Log")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for API service

type APIClient interface {
	StartJob(ctx context.Context, in *StartJobRequest, opts ...grpc.CallOption) (*StartJobResponse, error)
	DeleteJob(ctx context.Context, in *DeleteJobRequest, opts ...grpc.CallOption) (*DeleteJobResponse, error)
	ListJobs(ctx context.Context, in *ListJobsRequest, opts ...grpc.CallOption) (*ListJobsResponse, error)
	State(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (*StateResponse, error)
	Logs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (API_LogsClient, error)
}

type aPIClient struct {
	cc *grpc.ClientConn
}

func NewAPIClient(cc *grpc.ClientConn) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) StartJob(ctx context.Context, in *StartJobRequest, opts ...grpc.CallOption) (*StartJobResponse, error) {
	out := new(StartJobResponse)
	err := grpc.Invoke(ctx, "/types.API/StartJob", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) DeleteJob(ctx context.Context, in *DeleteJobRequest, opts ...grpc.CallOption) (*DeleteJobResponse, error) {
	out := new(DeleteJobResponse)
	err := grpc.Invoke(ctx, "/types.API/DeleteJob", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) ListJobs(ctx context.Context, in *ListJobsRequest, opts ...grpc.CallOption) (*ListJobsResponse, error) {
	out := new(ListJobsResponse)
	err := grpc.Invoke(ctx, "/types.API/ListJobs", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) State(ctx context.Context, in *StateRequest, opts ...grpc.CallOption) (*StateResponse, error) {
	out := new(StateResponse)
	err := grpc.Invoke(ctx, "/types.API/State", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) Logs(ctx context.Context, in *LogsRequest, opts ...grpc.CallOption) (API_LogsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_API_serviceDesc.Streams[0], c.cc, "/types.API/Logs", opts...)
	if err != nil {
		return nil, err
	}
	x := &aPILogsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type API_LogsClient interface {
	Recv() (*Log, error)
	grpc.ClientStream
}

type aPILogsClient struct {
	grpc.ClientStream
}

func (x *aPILogsClient) Recv() (*Log, error) {
	m := new(Log)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for API service

type APIServer interface {
	StartJob(context.Context, *StartJobRequest) (*StartJobResponse, error)
	DeleteJob(context.Context, *DeleteJobRequest) (*DeleteJobResponse, error)
	ListJobs(context.Context, *ListJobsRequest) (*ListJobsResponse, error)
	State(context.Context, *StateRequest) (*StateResponse, error)
	Logs(*LogsRequest, API_LogsServer) error
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_StartJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(StartJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(APIServer).StartJob(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _API_DeleteJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(DeleteJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(APIServer).DeleteJob(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _API_ListJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(ListJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(APIServer).ListJobs(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _API_State_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(StateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(APIServer).State(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _API_Logs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(APIServer).Logs(m, &aPILogsServer{stream})
}

type API_LogsServer interface {
	Send(*Log) error
	grpc.ServerStream
}

type aPILogsServer struct {
	grpc.ServerStream
}

func (x *aPILogsServer) Send(m *Log) error {
	return x.ServerStream.SendMsg(m)
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "types.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartJob",
			Handler:    _API_StartJob_Handler,
		},
		{
			MethodName: "DeleteJob",
			Handler:    _API_DeleteJob_Handler,
		},
		{
			MethodName: "ListJobs",
			Handler:    _API_ListJobs_Handler,
		},
		{
			MethodName: "State",
			Handler:    _API_State_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Logs",
			Handler:       _API_Logs_Handler,
			ServerStreams: true,
		},
	},
}

var fileDescriptor0 = []byte{
	// 367 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x53, 0x41, 0x4f, 0xea, 0x40,
	0x10, 0xa6, 0xdd, 0x42, 0x1e, 0xc3, 0xe3, 0x01, 0xc3, 0x0b, 0x34, 0xcd, 0x7b, 0x84, 0xec, 0x45,
	0xe2, 0x81, 0x18, 0xf4, 0x6a, 0xa2, 0x89, 0x17, 0x0d, 0x07, 0x83, 0x07, 0xcf, 0x45, 0x57, 0x52,
	0x83, 0xb4, 0x76, 0x97, 0x83, 0xbf, 0xc8, 0xbf, 0xe9, 0xee, 0xba, 0xdd, 0x85, 0x45, 0x6e, 0xb3,
	0xdf, 0xcc, 0x7c, 0xf3, 0xcd, 0x37, 0x2d, 0x34, 0xd3, 0x22, 0x9b, 0x16, 0x65, 0x2e, 0x72, 0xac,
	0x8b, 0x8f, 0x82, 0x71, 0xfa, 0x08, 0x9d, 0x07, 0x91, 0x96, 0xe2, 0x2e, 0x5f, 0x2e, 0xd8, 0xfb,
	0x96, 0x71, 0x81, 0x08, 0xd1, 0x26, 0x7d, 0x63, 0x71, 0x30, 0x0e, 0x26, 0xcd, 0x85, 0x8e, 0x15,
	0x96, 0x96, 0x2b, 0x1e, 0x87, 0x63, 0xa2, 0x30, 0x15, 0xe3, 0x3f, 0x49, 0x57, 0x8a, 0xec, 0x25,
	0x7d, 0x12, 0x3c, 0x26, 0xba, 0xd8, 0x01, 0x94, 0x42, 0xd7, 0x11, 0xf3, 0x22, 0xdf, 0x70, 0x86,
	0x7f, 0x20, 0xcc, 0x9e, 0x35, 0x6f, 0x7b, 0x21, 0x23, 0x55, 0x73, 0xc3, 0xd6, 0x4c, 0xb0, 0x9d,
	0xe9, 0x7e, 0x4d, 0x1f, 0x7a, 0x3b, 0x35, 0xdf, 0x44, 0xb4, 0x07, 0x9d, 0x79, 0xc6, 0x15, 0x37,
	0x37, 0x7d, 0x94, 0x03, 0x91, 0x4f, 0xbf, 0xdd, 0x2e, 0x13, 0xfe, 0xb0, 0x0c, 0x39, 0xb6, 0x4c,
	0xe4, 0x2d, 0x83, 0x03, 0x68, 0x70, 0x91, 0x8a, 0x2d, 0x8f, 0xeb, 0x3a, 0x65, 0x5e, 0x74, 0x06,
	0x5d, 0xa7, 0xc3, 0x2c, 0x39, 0x82, 0xe8, 0x55, 0xbe, 0xa5, 0x06, 0x32, 0x69, 0xcd, 0x60, 0xaa,
	0x7d, 0x9e, 0x2a, 0xf5, 0x1a, 0xa7, 0x23, 0xf8, 0x2d, 0x8d, 0x11, 0xec, 0xd8, 0xc2, 0x27, 0xd0,
	0x36, 0x79, 0x43, 0xe8, 0x86, 0x07, 0x7b, 0xc3, 0xff, 0x43, 0x6b, 0x9e, 0xaf, 0xf8, 0x31, 0x9e,
	0x21, 0x10, 0x99, 0xc6, 0x2e, 0x90, 0x75, 0xbe, 0x32, 0xad, 0x2a, 0x9c, 0x7d, 0x86, 0x40, 0xae,
	0xef, 0x6f, 0xf1, 0x12, 0x7e, 0x55, 0x17, 0xc2, 0x81, 0x91, 0xe9, 0x7d, 0x0b, 0xc9, 0xf0, 0x00,
	0x37, 0x17, 0xa8, 0xe1, 0x15, 0x34, 0xed, 0x61, 0xb0, 0xaa, 0xf3, 0xcf, 0x99, 0xc4, 0x87, 0x09,
	0xcb, 0x20, 0x05, 0x54, 0xee, 0x59, 0x01, 0xde, 0x59, 0xad, 0x00, 0xdf, 0x66, 0xd9, 0x7e, 0x01,
	0x75, 0x6d, 0x14, 0xf6, 0x9d, 0x48, 0x6b, 0x6b, 0xf2, 0x77, 0x1f, 0xb4, 0x5d, 0xa7, 0x10, 0x29,
	0xd7, 0x10, 0x2b, 0x62, 0x67, 0x61, 0x02, 0x0e, 0xa3, 0xb5, 0xb3, 0x60, 0xd9, 0xd0, 0xbf, 0xca,
	0xf9, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2f, 0xda, 0x21, 0x41, 0x37, 0x03, 0x00, 0x00,
}
