---
  language: go
  sudo: false
  notifications:
    email: true
  go:
    - 1.x
    - tip
  matrix:
    allow_failures:
      - go: tip
    fast_finish: true
  install:
    - go get github.com/golang/lint/golint
    - go get honnef.co/go/tools/cmd/staticcheck
  script:
    - make all
    - make cover
    - make release
  after_success:
    - bash <(curl -s https://codecov.io/bash)
  deploy:
    provider: releases
    api_key:
      secure: ""
    file:
      - cross/k8s-aks-dns-ingress-linux-amd64.md5
      - cross/k8s-aks-dns-ingress-windows-386.sha256
      - cross/k8s-aks-dns-ingress-linux-arm
      - cross/k8s-aks-dns-ingress-darwin-amd64.md5
      - cross/k8s-aks-dns-ingress-darwin-amd64
      - cross/k8s-aks-dns-ingress-solaris-amd64.md5
      - cross/k8s-aks-dns-ingress-linux-arm64.sha256
      - cross/k8s-aks-dns-ingress-linux-arm.sha256
      - cross/k8s-aks-dns-ingress-linux-386.sha256
      - cross/k8s-aks-dns-ingress-darwin-386.md5
      - cross/k8s-aks-dns-ingress-windows-386.md5
      - cross/k8s-aks-dns-ingress-freebsd-amd64.md5
      - cross/k8s-aks-dns-ingress-linux-arm64.md5
      - cross/k8s-aks-dns-ingress-linux-arm64
      - cross/k8s-aks-dns-ingress-freebsd-amd64.sha256
      - cross/k8s-aks-dns-ingress-freebsd-386.md5
      - cross/k8s-aks-dns-ingress-linux-amd64.sha256
      - cross/k8s-aks-dns-ingress-linux-386.md5
      - cross/k8s-aks-dns-ingress-freebsd-386
      - cross/k8s-aks-dns-ingress-solaris-amd64.sha256
      - cross/k8s-aks-dns-ingress-windows-amd64
      - cross/k8s-aks-dns-ingress-windows-amd64.md5
      - cross/k8s-aks-dns-ingress-windows-amd64.sha256
      - cross/k8s-aks-dns-ingress-linux-arm.md5
      - cross/k8s-aks-dns-ingress-darwin-386.sha256
      - cross/k8s-aks-dns-ingress-darwin-amd64.sha256
      - cross/k8s-aks-dns-ingress-windows-386
      - cross/k8s-aks-dns-ingress-solaris-amd64
      - cross/k8s-aks-dns-ingress-darwin-386
      - cross/k8s-aks-dns-ingress-linux-386
      - cross/k8s-aks-dns-ingress-freebsd-amd64
      - cross/k8s-aks-dns-ingress-freebsd-386.sha256
      - cross/k8s-aks-dns-ingress-linux-amd64
    skip_cleanup: true
    on:
      tags: true
